config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  def show
    @flat = Flat.find(params[:id])
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="navbar bg-light">
  <h1 class="navbar-brand mx-3">Simple Airbnb</h1>
  <div class="d-flex flex-row">
    <div class="nav-item input-group">
      <input type="text" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-outline-success" type="button">Search</button>
      </div>
    </div>
    <div class="nav-item btn btn-outline-primary custom-btn mx-2">
      <%= link_to "Add Flat", new_flat_path %>
    </div>
  </div>
</div>

<div class="container">
  <h2>All our flats</h2>
  <div class="row row-cols-1 row-cols-md-4">
    <% @flats.each do |flat| %>
      <div class="col mb-4">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <h3><%= flat.name %></h3>
            <p><%= flat.address %></p>
            <div class="d-flex">
              <div class="d-flex align-items-center">
                <i class="fa-solid fa-user-group"></i>
                <span><%= flat.number_of_guests %></span>
              </div>
              <div class="d-flex align-items-center mx-2">
                <i class="fa-solid fa-euro-sign"></i>
                <span><%= flat.price_per_night %></span>
              </div>
            </div>
          </div>
          <div class="card-footer text-muted">
            <%= link_to "More info", flat_path(flat) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="navbar bg-light">
  <h1 class="navbar-brand mx-3">Simple Airbnb</h1>
  <div class="d-flex flex-row">
    <div class="nav-item input-group">
      <input type="text" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-outline-success" type="button">Search</button>
      </div>
    </div>
    <div class="nav-item btn btn-outline-primary custom-btn mx-2">
      <%= link_to "Add Flat", new_flat_path %>
    </div>
  </div>
</div>

<div class="container w-50 my-3 bg-light">
  <div class="p-3">
    <h1 class="display-4 mt-2 mb-4">Add a new flat</h1>
    <%= simple_form_for(@flat) do |f| %>
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :description %>
      <%= f.input :price_per_night %>
      <%= f.input :number_of_guests %>
      <button type="submit" class="btn btn-primary">Create Flat</button>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="navbar bg-light">
  <h1 class="navbar-brand mx-3">Simple Airbnb</h1>
  <div class="d-flex flex-row">
    <div class="nav-item btn btn-outline-primary custom-btn mx-2">
      <%= link_to "Add Flat", new_flat_path %>
    </div>
  </div>
</div>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.rocketmortgage.com/resources-cmsassets/RocketMortgage.com/Article_Images/Large_Images/Stock-Airbnb-Home-AdobeStock-298309756%20-%20Copy-2.jpeg);">
</div>

<div class="container">
  <div class="row my-4">
    <div class="col-8">
      <div class="card mb-3">
        <div class="card-body bg-light">
          <h1><%= @flat.name %></h1>
          <p><%= @flat.address %></p>
        </div>
      </div>

      <div class="card">
        <div class="card-body bg-light">
          <h2>A bit more about this flat...</h2>
          <%= @flat.description %>
        </div>
      </div>
    </div>

    <div class="col-4">
      <div class="card mb-3">
        <div class="card-body bg-light">
          <h3>Book this place!</h3>
        </div>
      </div>

      <div class="card mb-3">
        <div class="card-body bg-light">
          <h3>Details</h3>
        </div>
      </div>

      <div class="card">
        <div class="card-body bg-light">
          <h3>Share</h3>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>